export const CREATE_TODO = 'CREATE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const UNCOMPLETED_TODO = 'UNCOMPLETED_TODO'
export const LOAD_TOTOS_IN_PROGRESS = 'LOAD_TOTOS_IN_PROGRESS'
export const LOAD_TOTOS_SUCCESS = 'LOAD_TOTOS_SUCCESS'
export const LOAD_TOTOS_FAILURE = 'LOAD_TOTOS_FAILURE'
